name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
          pnpm install

      - name: Build
        run: pnpm run build

  build-docker-image:
    needs: [ build ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/panchobot .

      - name: Log into Docker and upload image
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push ${{secrets.DOCKER_USERNAME}}/panchobot


  deploy:
    needs: [ build, build-docker-image ]
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Vultr VPS, pull docker image and run the image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY}}
          script: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker kill $(docker ps -q)
            docker system prune --all --force
            docker pull ${{ secrets.DOCKER_USERNAME }}/panchobot:latest
            docker run --env-file ./secrets/panchobot_secrets --rm -d ${{ secrets.DOCKER_USERNAME }}/panchobot:latest

    