name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
          pnpm install

      - name: Build
        run: pnpm run build

    deploy:
      needs: [ build ]
      if: false
      runs-on: self-hosted

      steps:
        - name: SSH into Vultr VPS, pull docker image and run the image
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VULTR_IP_ADDRESS }}
            username: ${{ secrets.VULTR_USERNAME }}
            password: ${{ secrets.VULTR_PASSWORD }}
            script: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker kill $(docker ps -q)
              docker system prune --all --force
              docker pull ${{ secrets.DOCKER_USERNAME }}/panchobot:latest
              docker run --rm -d ${{ secrets.DOCKER_USERNAME }}/panchobot:latest
    