name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
          pnpm install

      - name: Build
        run: pnpm run build     

      # - name: Run tests
      #   run: pnpm test