# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install --no-frozen-lockfile
    - run: sudo rm -rf /home/pancho/PanchoBot/node_modules
    - run: sudo cp -uaR . /home/pancho/PanchoBot
    - run: screen -X -S panchobot quit
      continue-on-error: true
    - run: cd /home/pancho/PanchoBot && pnpm run build
    - run: screen -dmS panchobot node app.js
